name: subtree-sync
on:
  - push
env:
  GITSPLIT_GITHUB_TOKEN: ${{ secrets.INPUT_GITHUB_TOKEN }}
jobs:
  monorepo-split:
    name: Split Git Repositories
    runs-on:
      - ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress

      - name: Split monorepo
        run: composer git:split
